services:

  database:
    profiles: [ all, backend, database ]
    build: database
    image: dolores/database:latest
    container_name: dolores-database
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - database/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s

  backend:
    profiles: [ all, backend ]
    build: backend
    image: dolores/backend:latest
    container_name: dolores-backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/api/v1/healthcheck/ > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s

  tools:
    profiles: [ all, tools ]
    build: tools
    image: dolores/tools:latest
    container_name: dolores-tools
    ports:
      - "8002:8002"
    volumes:
      - repos:/home/dolores/repos
    env_file:
      - tools/.env
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8002/api/v1/healthcheck > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s

  inference:
    profiles: [ all, inference ]
    build: inference
    image: dolores/inference:latest
    container_name: dolores-inference
    ports:
      - "8001:8001"
    volumes:
      - repos:/home/dolores/repos
    env_file:
      - inference/.env
    depends_on:
      backend:
        condition: service_healthy
      tools:
        condition: service_healthy

volumes:
  database:
  repos:
