# helm/templates/secret.yaml

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.fullname" . }}-env
  labels:
    {{- include "database.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.envSecret.data | nindent 2 }}
