---
name: CI Pipeline

on:
  push:
    branches: [ "**" ]
    paths:
      - ".github/workflows/**"
      - "backend/**"
      - "database/**"
      - "inference/**"
      - "tools/**"
  workflow_dispatch:
    inputs:
      dockerfile_lint_check_failure_threshold:
        description: "Threshold to fail the Dockerfile lint check."
        type: choice
        options: [error, warning, info, style, ignore]
        default: error
      sbom_scan_failure_threshold:
        description: "Threshold to fail the SBOM scan."
        type: choice
        options: [low, high, critical]
        default: low
  schedule:
    - cron: '00 12 * * *' 

jobs:

  secrets:
    name: Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v6
      - name: Run Trufflehog
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: false

  code-lint:
    name: Code Lint Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - backend
          - inference
          - tools
    steps:
      - name: Clone the repository
        uses: actions/checkout@v7
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install Python dependencies
        run: python -m pip install black
      - name: Check code formatting
        run: black --diff --color --check ${{ matrix.container }}

  dockerfile-lint:
    name: Dockerfile Lint Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - backend
          - inference
          - tools
    steps:
      - uses: actions/checkout@v7
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: ${{ matrix.container }}/Dockerfile
          failure-threshold: ${{ github.event.inputs.dockerfile_lint_check_failure_threshold || 'error' }}
          format: json

  sast:
    name: SAST Scan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - backend
          - inference
          - tools
    container:
      image: semgrep/semgrep
    steps:
      - name: Clone the repository
        uses: actions/checkout@v6
      - name: Run Semgrep
        run: semgrep scan --config auto ${{ matrix.container }}

  sca:
    name: SBOM Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    strategy:
      fail-fast: false
      matrix:
        container:
          - backend
          - inference
          - tools
    steps:
      - uses: actions/checkout@v6
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx
          path: ${{ matrix.container }}
          output-file: sbom-${{ matrix.container }}.json
          artifact-name: sbom-${{ matrix.container }}.json
      - name: Scan SBOM
        uses: anchore/scan-action@v7
        with:
          sbom: sbom-${{ matrix.container }}.json
          severity-cutoff: ${{ github.event.inputs.sbom_scan_failure_threshold || 'low' }}
